import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { ApolloWrapper } from "@/app/ApolloWrapper";

import "./globals.css";

export const metadata: Metadata = {
  title: "Leonardo AI Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <ChakraProvider>{children}</ChakraProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
